# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  color: 'green'
  icon: 'box'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  is_ci:  # id of input
    description: 'is ci'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}